spring.application.name=despesas

## PostgreSQL
spring.datasource.url=jdbc:postgresql://ep-twilight-moon-acwrtu3o-pooler.sa-east-1.aws.neon.tech/aulas
spring.datasource.username=senaipato
spring.datasource.password=SenaiPatoBranco
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true